name: Sync Upstream Changes

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Upstream Remote
      run: git remote add upstream https://github.com/Lissy93/portainer-templates

    - name: Fetch and Merge Changes
      run: |
        git fetch upstream
        git checkout main
        git merge upstream/main
        git push origin main
